name: Pulumi Preview
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
      
jobs:

  preview_updates:
    name: Preview Updates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Get Pull Request Files
        run: |
          
          echo 'PR_FILES<<EOF' >> $GITHUB_ENV
          gh pr view ${{ github.event.number }} --json files --jq '.files.[].path' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip' # caching pip dependencies
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r resource_group/requirements.txt
          python -m pip install -r key_vault/requirements.txt
        
      - name: Resource Group - Pulumi preview
        uses: pulumi/actions@v4
        if: ${{ contains(env.PR_FILES, 'resource_group/') }}
        id: resource_group
        with:
          work-dir: resource_group
          command: preview
          stack-name: dev
          cloud-url: azblob://iacstate
          diff: true
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          PULUMI_CONFIG_PASSPHRASE : ""
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          
      - name: Resource Group - Summary
        if: ${{ steps.resource_group.outcome == 'success' }}
        run: |
          echo ":arrow_forward: ${{ steps.resource_group.outputs.output }}" >> $GITHUB_STEP_SUMMARY

      - name: Key Vault - Pulumi preview
        uses: pulumi/actions@v4
        if: ${{ contains(env.PR_FILES, 'key_vault/') }}
        id: key_vault
        with:
          work-dir: key_vault
          command: preview
          stack-name: dev
          cloud-url: azblob://iacstate
          diff: true
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          PULUMI_CONFIG_PASSPHRASE : ""
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          
      - name: Key Vault - Summary
        run: |
          echo ":arrow_forward: ${{ steps.key_vault.outputs.output }}" >> $GITHUB_STEP_SUMMARY
